version: 0.2

phases:
  pre_build:
    commands:

      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 339712771390.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t ecr1 .
      - echo Tagging the current green image as blue if it exists...
      - docker pull 339712771390.dkr.ecr.us-east-1.amazonaws.com/ecr1:green || true
      - docker tag 339712771390.dkr.ecr.us-east-1.amazonaws.com/ecr1:green 339712771390.dkr.ecr.us-east-1.amazonaws.com/ecr1:blue || true
      - echo Tagging the Docker image as green...
      - docker tag ecr1:latest 339712771390.dkr.ecr.us-east-1.amazonaws.com/ecr1:green


  post_build:
    commands:

      - echo Pushing the Docker image with blue tag to ECR if it exists...
      - docker push 339712771390.dkr.ecr.us-east-1.amazonaws.com/ecr1:blue || true
      - docker push 339712771390.dkr.ecr.us-east-1.amazonaws.com/ecr1:green
      - echo Writing image definitions file...
      - printf '[{"name":"mywebsite","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
